// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiL1tnJOqFoBVZYgTj7ELgYCH5HmJOhVU',
    appId: '1:443808242441:web:48e89108f77f7fef23d1d8',
    messagingSenderId: '443808242441',
    projectId: 'umart-app-3bd8a',
    authDomain: 'umart-app-3bd8a.firebaseapp.com',
    storageBucket: 'umart-app-3bd8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVazZ6U3290F2lyx4sQwSqFnOUntUDpg',
    appId: '1:443808242441:android:753f250dff20fc9023d1d8',
    messagingSenderId: '443808242441',
    projectId: 'umart-app-3bd8a',
    storageBucket: 'umart-app-3bd8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy_Zmlz79RR_hVU5NwYGlU6-pX3IB_p4I',
    appId: '1:443808242441:ios:55d5ebbb30ddffd723d1d8',
    messagingSenderId: '443808242441',
    projectId: 'umart-app-3bd8a',
    storageBucket: 'umart-app-3bd8a.firebasestorage.app',
    iosBundleId: 'com.example.umartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy_Zmlz79RR_hVU5NwYGlU6-pX3IB_p4I',
    appId: '1:443808242441:ios:55d5ebbb30ddffd723d1d8',
    messagingSenderId: '443808242441',
    projectId: 'umart-app-3bd8a',
    storageBucket: 'umart-app-3bd8a.firebasestorage.app',
    iosBundleId: 'com.example.umartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiL1tnJOqFoBVZYgTj7ELgYCH5HmJOhVU',
    appId: '1:443808242441:web:1e0607fd8c72065e23d1d8',
    messagingSenderId: '443808242441',
    projectId: 'umart-app-3bd8a',
    authDomain: 'umart-app-3bd8a.firebaseapp.com',
    storageBucket: 'umart-app-3bd8a.firebasestorage.app',
  );
}
